test

diff --git a/RBS_src/rbs b/RBS_src/rbs
--- a/RBS_src/rbs
+++ b/RBS_src/rbs
@@ -11,6 +11,7 @@
 # -> Setup doas (instead of sudo)
 # Try to do these steps manually and write it all again...
 
+
 mkdir /tmp/tmprbs
 read -p "Which aurhelper would you like to install (default is yay): " aurhelper
 
@@ -23,27 +24,37 @@ internet()
 	ping -c 2 www.example.com 2>&- >/dev/null || (echo "You're not connected to the internet. Check out that NetworkManager is started" && false)
 }
 
+pimp_pacman(){
+	grep "^Color" /etc/pacman.conf >/dev/null || sed -i "s/^#Color$/Color/" /etc/pacman.conf
+}
 
 installer(){
 	sudo pacman --noconfirm --needed -S "$*" >/dev/null 2>&1
 }
 
 refresh_keyrings(){
-	sudo pacman -Sy archlinux-keyring >/dev/null 2>&1
+	sudo pacman --noconfirm --needed -Sy archlinux-keyring >/dev/null 2>&1
 }
 
 install_yay(){
-	[ -f "/usr/bin/$aurhelper"] || (
-	cd /tmp
-	rm -rf /tmp/"$aurhelper"*
+	[ -f "/usr/bin/$aurhelper" ] || (
+	cd /tmp/tmprbs
+	rm -rf /tmp/tmprbs/"$aurhelper"*
 	curl -sO https://aur.archlinux.org/cgit/aur.git/snapshot/"$aurhelper".tar.gz &&
-	sudo  tar -xvf "$aurhelper".tar.gz >/dev/null 2>&1 &&
+	tar -xvf "$aurhelper".tar.gz >/dev/null 2>&1 &&
 	cd "$aurhelper" &&
-	sudo makepkg --noconfirm -si >/dev/null 2>&1
-	cd /tmp || return)
+	makepkg --noconfirm -si >/dev/null 2>&1
+	cd /tmp/tmprbs)
 }
 
-
+install_progs(){
+	while IFS=, read -r tag prog comment; do
+		case "$tag" in
+			"A") sudo $aurhelper -S --noconfirm $prog ;; #>/dev/null 2>&1 ;;
+			*) installer $prog ;; #>/dev/null 2>&1 ;;
+		esac
+	done < progs.csv
+}
 
 
 
@@ -62,14 +73,13 @@ clear_tmprbs(){
 
 
 remove_all(){
-	echo "An error has occured. Fix the issue and rerun this script."
+	echo "An error occured"
 	clear_tmprbs
 }
 
 
 
-internet && refresh_keyrings && install_yay && clear_tmp || remove_all
-
+internet && pimp_pacman && refresh_keyrings && install_yay && install_progs && clear_tmprbs || remove_all
 
 
 
