shellcheck passed

diff --git a/RBS_src/rbs b/RBS_src/rbs
--- a/RBS_src/rbs
+++ b/RBS_src/rbs
@@ -4,16 +4,13 @@
 # Thanks to this webpage (http://xn--rpa.cc/irl/term.html), I'm able to use ANSI escape sequences.
 
 # Is first meant for arch, but will then be extended to void and debian
-# Goal of this script :
-#
-# -> Install keyboard layout
-# -> Installing dotfiles (which of course need to be reviewed and updated...)
-
+# To be sure to have no error when shellcheck running:
+# shellcheck disable=SC1091
 
 mkdir /tmp/tmprbs >/dev/null 2>&1
 username="$(who | cut -d " " -f1)"
 dot_repo="temp_dotfiles"
-read -p "Which aurhelper would you like to install (default is yay): " aurhelper
+read -rp "Which aurhelper would you like to install (default is yay): " aurhelper
 [ -z "$aurhelper" ] && aurhelper="yay"
 
 internet()
@@ -35,13 +32,13 @@ refresh_keyrings(){
 install_yay(){
 	[ -f "/usr/bin/$aurhelper" ] || (
 	echo "Manually installing ${aurhelper}, this may take several minutes..."
-	cd /tmp/tmprbs
+	cd /tmp/tmprbs || exit
 	rm -rf /tmp/tmprbs/"$aurhelper"*
 	curl -sO https://aur.archlinux.org/cgit/aur.git/snapshot/"$aurhelper".tar.gz &&
 	tar -xvf "$aurhelper".tar.gz >/dev/null 2>&1 &&
 	cd "$aurhelper" &&
 	makepkg --noconfirm -si >/dev/null 2>&1
-	cd /tmp/tmprbs)
+	cd /tmp/tmprbs || exit)
 }
 
 # 3 escape seq meaning: back 12 columns, erase end of line and then write in bold  and green [DONE] and go back to the line
@@ -55,56 +52,56 @@ writing_bold_red(){
 
 installer(){
 	install_mess="Installing $1... "
-	printf '%s%*s' "$install_mess" "$((($(tput cols) / 2) - ${#install_mess}))"
+	printf '%s%*s' "$install_mess" "$((($(tput cols) / 2) - ${#install_mess}))" ""
 	printf "[INSTALLING]"
-	sudo pacman --noconfirm --needed -S "$1" >/dev/null 2>&1 && writing_bold_green || writing_bold_red
+	(sudo pacman --noconfirm --needed -S "$1" >/dev/null 2>&1 && writing_bold_green) || writing_bold_red
 }
 
 aur_installer(){
 	pacman -Qqm | grep "^$1$" >/dev/null 2>&1 && return
 	install_mess="Installing $1... "
-	printf '%s%*s' "$install_mess" "$((($(tput cols) / 2) - ${#install_mess}))"
+	printf '%s%*s' "$install_mess" "$((($(tput cols) / 2) - ${#install_mess}))" ""
 	printf "[INSTALLING]"
-	$aurhelper --noconfirm --useask -S "$1" >/dev/null 2>&1 && writing_bold_green || writing_bold_red
+	($aurhelper --noconfirm --useask -S "$1" >/dev/null 2>&1 && writing_bold_green) || writing_bold_red
 
 }
 
 make_git_inst(){
-	pname="$(basename $1)"
+	pname="$(basename "$1")"
 	install_mess="Installing ${pname}... "
-	printf '%s%*s' "$install_mess" "$((($(tput cols) / 2) - ${#install_mess}))"
+	printf '%s%*s' "$install_mess" "$((($(tput cols) / 2) - ${#install_mess}))" ""
 	printf "[INSTALLING]"
-	cd /tmp/tmprbs
-	git clone --depth 1 $1 >/dev/null 2>&1
-	cp -rfT $pname /home/${username}/.config/${pname} >/dev/null 2>&1
-	cd $pname
+	cd /tmp/tmprbs || exit
+	git clone --depth 1 "$1" >/dev/null 2>&1
+	cp -rfT "$pname" /home/"${username}"/.config/"${pname}" >/dev/null 2>&1
+	cd "$pname" || exit
 	make >/dev/null 2>&1
-	sudo make install >/dev/null 2>&1 && writing_bold_green || writing_bold_red
+	(sudo make install >/dev/null 2>&1 && writing_bold_green) || writing_bold_red
 }
 
 install_progs(){
-	while IFS=, read -r tag prog comment; do
+	while IFS=, read -r tag prog ; do
 		case "$tag" in
-			"A") aur_installer $prog ;;
-			"G") make_git_inst $prog ;;
-			*) installer $prog ;;
+			"A") aur_installer "$prog" ;;
+			"G") make_git_inst "$prog" ;;
+			*) installer "$prog" ;;
 		esac
 	done < progs.csv
 }
 
 manually_inst_dwm(){
 	install_mess="Installing dwm... "
-	printf '%s%*s' "$install_mess" "$((($(tput cols) / 2) - ${#install_mess}))"
+	printf '%s%*s' "$install_mess" "$((($(tput cols) / 2) - ${#install_mess}))" ""
 	printf "[INSTALLING]"
-	cd /tmp/tmprbs
+	cd /tmp/tmprbs || exit
 	git clone --depth 1 https://github.com/LukeSmithxyz/dwm >/dev/null 2>&1
-	cd dwm
+	cd dwm || exit
 	sed -i "/\/share\/dwm/d" Makefile
 	cd ..
-	cp -rfT dwm /home/${username}/.config/dwm >/dev/null 2>&1
-	cd dwm
+	cp -rfT dwm /home/"${username}"/.config/dwm >/dev/null 2>&1
+	cd dwm || exit
 	make >/dev/null 2>&1
-	sudo make install >/dev/null 2>&1 && writing_bold_green || writing_bold_red
+	(sudo make install >/dev/null 2>&1 && writing_bold_green) || writing_bold_red
 }
 
 remove_noise(){
@@ -115,7 +112,7 @@ remove_noise(){
 
 base_dir(){
 	echo "Creating some folders..."
-	cd /home/"${username}"/
+	cd /home/"${username}"/ ||exit
 	mkdir Dl .Gfre Vids Repos Docs
 }
 
@@ -148,15 +145,15 @@ Exec = /usr/bin/pkill -RTMIN+8 dwmblocks" | sudo tee /usr/share/libalpm/hooks/st
 
 insert_dotfiles(){
 	echo "Inserting and managing dotfiles..."
-	cd /tmp/tmprbs
+	cd /tmp/tmprbs || exit
 	git clone --depth 1 https://github.com/Rhylx/${dot_repo}  >/dev/null 2>&1
 	sudo mv ${dot_repo}/.local/tty_keymap/keymap /usr/share/kbd/keymaps/i386/qwerty/my_custom_keymap.map
 	echo "KEYMAP=my_custom_keymap" | sudo tee /etc/vconsole.conf >/dev/null 2>&1
-	cp -rfT temp_dotfiles/ /home/${username}/ >/dev/null 2>&1
-	cd
+	cp -rfT temp_dotfiles/ /home/"${username}"/ >/dev/null 2>&1
+	cd || exit
 	sudo rm -rf .git
 	rm -f README.md
-	mkdir -p /home/${username}/.local/share/xorg
+	mkdir -p /home/"${username}"/.local/share/xorg
 	. /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
 }
 
@@ -174,13 +171,13 @@ clear_tmprbs(){
 }
 
 remove_all(){
-	echo "An error occured"
+	echo "An error occured, please fix it an rerun the script"
 	clear_tmprbs
 }
 
 
 
-clear ; internet && pimp_pacman && refresh_keyrings && install_yay && install_progs && manually_inst_dwm && remove_noise && base_dir && pacman_statusbar && insert_dotfiles && move_gpg && clear_tmprbs || remove_all
+clear ; (internet && pimp_pacman && refresh_keyrings && install_yay && install_progs && manually_inst_dwm && remove_noise && base_dir && pacman_statusbar && insert_dotfiles && move_gpg && clear_tmprbs) || remove_all
 
 # Main structure of script is finished for arch. Now, there remains to rebuild all soft and config files # and to add then slowly in prog.csv...
 
