test

diff --git a/Install/arch_rbs b/Install/arch_rbs
--- a/Install/arch_rbs
+++ b/Install/arch_rbs
@@ -18,7 +18,7 @@ export "DIST=$(./detect_distrib)$" #once installation done write this to /etc/en
 
 internet()
 {
-	ping -c 2 www.example.com || echo "You're not connected to the internet. Check out your connection"
+	ping -c 2 www.example.com 2>&- 1>/dev/null || (echo "You're not connected to the internet. Check out your connection" && false)
 }
 
 
@@ -71,7 +71,7 @@ grub_install(){
 }
 
 remove_all(){
-echo "An error has occured. Fix the issue and rerun this script"
+echo "An error has occured. Fix the issue and rerun this script."
 }
 
 
